# Generated by Django 4.0.4 on 2022-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_character_options_remove_anime_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer',
            field=models.CharField(default='', max_length=500, verbose_name='Трайлер'),
        ),
    ]
