# Generated by Django 4.0.4 on 2022-05-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_anime_trailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезда рейтинга'},
        ),
    ]
